/*
Copyright 2025 LC.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	applyconfigurationreclustercomv1alpha1 "github.com/lcereser6/recluster-sync/apis/client/applyconfiguration/recluster.com/v1alpha1"
	scheme "github.com/lcereser6/recluster-sync/apis/client/clientset/versioned/scheme"
	reclustercomv1alpha1 "github.com/lcereser6/recluster-sync/apis/recluster.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// RcNodesGetter has a method to return a RcNodeInterface.
// A group's client should implement this interface.
type RcNodesGetter interface {
	RcNodes(namespace string) RcNodeInterface
}

// RcNodeInterface has methods to work with RcNode resources.
type RcNodeInterface interface {
	Create(ctx context.Context, rcNode *reclustercomv1alpha1.RcNode, opts v1.CreateOptions) (*reclustercomv1alpha1.RcNode, error)
	Update(ctx context.Context, rcNode *reclustercomv1alpha1.RcNode, opts v1.UpdateOptions) (*reclustercomv1alpha1.RcNode, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, rcNode *reclustercomv1alpha1.RcNode, opts v1.UpdateOptions) (*reclustercomv1alpha1.RcNode, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*reclustercomv1alpha1.RcNode, error)
	List(ctx context.Context, opts v1.ListOptions) (*reclustercomv1alpha1.RcNodeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *reclustercomv1alpha1.RcNode, err error)
	Apply(ctx context.Context, rcNode *applyconfigurationreclustercomv1alpha1.RcNodeApplyConfiguration, opts v1.ApplyOptions) (result *reclustercomv1alpha1.RcNode, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, rcNode *applyconfigurationreclustercomv1alpha1.RcNodeApplyConfiguration, opts v1.ApplyOptions) (result *reclustercomv1alpha1.RcNode, err error)
	RcNodeExpansion
}

// rcNodes implements RcNodeInterface
type rcNodes struct {
	*gentype.ClientWithListAndApply[*reclustercomv1alpha1.RcNode, *reclustercomv1alpha1.RcNodeList, *applyconfigurationreclustercomv1alpha1.RcNodeApplyConfiguration]
}

// newRcNodes returns a RcNodes
func newRcNodes(c *ReclusterV1alpha1Client, namespace string) *rcNodes {
	return &rcNodes{
		gentype.NewClientWithListAndApply[*reclustercomv1alpha1.RcNode, *reclustercomv1alpha1.RcNodeList, *applyconfigurationreclustercomv1alpha1.RcNodeApplyConfiguration](
			"rcnodes",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *reclustercomv1alpha1.RcNode { return &reclustercomv1alpha1.RcNode{} },
			func() *reclustercomv1alpha1.RcNodeList { return &reclustercomv1alpha1.RcNodeList{} },
		),
	}
}
