/*
Copyright 2025 LC.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	applyconfigurationreclustercomv1alpha1 "github.com/lcereser6/recluster-sync/apis/client/applyconfiguration/recluster.com/v1alpha1"
	scheme "github.com/lcereser6/recluster-sync/apis/client/clientset/versioned/scheme"
	reclustercomv1alpha1 "github.com/lcereser6/recluster-sync/apis/recluster.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// RcPoliciesGetter has a method to return a RcPolicyInterface.
// A group's client should implement this interface.
type RcPoliciesGetter interface {
	RcPolicies(namespace string) RcPolicyInterface
}

// RcPolicyInterface has methods to work with RcPolicy resources.
type RcPolicyInterface interface {
	Create(ctx context.Context, rcPolicy *reclustercomv1alpha1.RcPolicy, opts v1.CreateOptions) (*reclustercomv1alpha1.RcPolicy, error)
	Update(ctx context.Context, rcPolicy *reclustercomv1alpha1.RcPolicy, opts v1.UpdateOptions) (*reclustercomv1alpha1.RcPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, rcPolicy *reclustercomv1alpha1.RcPolicy, opts v1.UpdateOptions) (*reclustercomv1alpha1.RcPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*reclustercomv1alpha1.RcPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*reclustercomv1alpha1.RcPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *reclustercomv1alpha1.RcPolicy, err error)
	Apply(ctx context.Context, rcPolicy *applyconfigurationreclustercomv1alpha1.RcPolicyApplyConfiguration, opts v1.ApplyOptions) (result *reclustercomv1alpha1.RcPolicy, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, rcPolicy *applyconfigurationreclustercomv1alpha1.RcPolicyApplyConfiguration, opts v1.ApplyOptions) (result *reclustercomv1alpha1.RcPolicy, err error)
	RcPolicyExpansion
}

// rcPolicies implements RcPolicyInterface
type rcPolicies struct {
	*gentype.ClientWithListAndApply[*reclustercomv1alpha1.RcPolicy, *reclustercomv1alpha1.RcPolicyList, *applyconfigurationreclustercomv1alpha1.RcPolicyApplyConfiguration]
}

// newRcPolicies returns a RcPolicies
func newRcPolicies(c *ReclusterV1alpha1Client, namespace string) *rcPolicies {
	return &rcPolicies{
		gentype.NewClientWithListAndApply[*reclustercomv1alpha1.RcPolicy, *reclustercomv1alpha1.RcPolicyList, *applyconfigurationreclustercomv1alpha1.RcPolicyApplyConfiguration](
			"rcpolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *reclustercomv1alpha1.RcPolicy { return &reclustercomv1alpha1.RcPolicy{} },
			func() *reclustercomv1alpha1.RcPolicyList { return &reclustercomv1alpha1.RcPolicyList{} },
		),
	}
}
