/*
Copyright 2025 LC.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	versioned "github.com/lcereser6/recluster-sync/apis/client/clientset/versioned"
	internalinterfaces "github.com/lcereser6/recluster-sync/apis/client/informers/externalversions/internalinterfaces"
	reclustercomv1alpha1 "github.com/lcereser6/recluster-sync/apis/client/listers/recluster.com/v1alpha1"
	apisreclustercomv1alpha1 "github.com/lcereser6/recluster-sync/apis/recluster.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// RcnodeInformer provides access to a shared informer and lister for
// Rcnodes.
type RcnodeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() reclustercomv1alpha1.RcnodeLister
}

type rcnodeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewRcnodeInformer constructs a new informer for Rcnode type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRcnodeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRcnodeInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredRcnodeInformer constructs a new informer for Rcnode type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRcnodeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ReclusterV1alpha1().Rcnodes(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ReclusterV1alpha1().Rcnodes(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ReclusterV1alpha1().Rcnodes(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ReclusterV1alpha1().Rcnodes(namespace).Watch(ctx, options)
			},
		},
		&apisreclustercomv1alpha1.Rcnode{},
		resyncPeriod,
		indexers,
	)
}

func (f *rcnodeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRcnodeInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *rcnodeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisreclustercomv1alpha1.Rcnode{}, f.defaultInformer)
}

func (f *rcnodeInformer) Lister() reclustercomv1alpha1.RcnodeLister {
	return reclustercomv1alpha1.NewRcnodeLister(f.Informer().GetIndexer())
}
