#mutatingwebhookconfig.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: recluster-sync-pod-gate
webhooks:
  - name: gatepods.recluster.com
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 5
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
    clientConfig:
      service:
        name: {{ .Values.webhook.serviceName }}
        namespace: {{ .Release.Namespace }}
        path: /mutate-v1-pod
        port: {{ .Values.webhook.port }}
      caBundle: {{ .Values.webhook.caBundle | default "" | quote }}
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: ["kube-system","kube-public","kube-node-lease"]