# resources/turbo-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: turbo-echo
  labels: { app: turbo-echo }
spec:
  replicas: 2
  selector:
    matchLabels: { app: turbo-echo }
  template:
    metadata:
      labels: { app: turbo-echo }
      annotations:
        recluster.io/policy: fast-boot          # 🔗 tells rc-sync which policy to use
    spec:
      # ❶ Node-affinity makes the pod UN-schedulable until the RcNode is up
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: recluster.io/pool
                operator: In
                values: ["smoke-1"]            # pool we want (choose any RcNode name)

      # ❷ Tolerate the taint that rc-sync puts on the node
      tolerations:
      - key: "recluster.io/pool"
        operator: "Equal"
        value: "smoke-1"
        effect: "NoSchedule"

      containers:
      - name: web
        image: hashicorp/http-echo
        args: ["-text=hello from turbo"]