---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - recluster.recluster.com
  resources:
  - rcnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - recluster.recluster.com
  resources:
  - rcnodes/finalizers
  verbs:
  - update
- apiGroups:
  - recluster.recluster.com
  resources:
  - rcnodes/status
  verbs:
  - get
  - patch
  - update
