#!/usr/bin/env bash
set -euo pipefail
REG=ghcr.io/lcereser6
kind delete cluster || true
kind create cluster --image kindest/node:v1.30.0

KWOK=v0.5.2
curl -sL https://github.com/kubernetes-sigs/kwok/releases/download/$KWOK/kwok.yaml | kubectl apply -f -
curl -sL https://github.com/kubernetes-sigs/kwok/releases/download/$KWOK/stage-fast.yaml | kubectl apply -f -

kind load docker-image $REG/cluster-autoscaler:v1.30.0-recluster
kind load docker-image $REG/recluster-sync:dev

# Install the Rcnode CRD generated by kubebuilder
kubectl apply -f recluster-sync/config/crd/bases

# Deploy CA (uses image we just loaded)
helm install ca ca-recluster/charts/recluster-ca \
  --set image.repository=$REG/cluster-autoscaler --set image.tag=v1.30.0-recluster -n kube-system

# Deploy the controller in KWOK mode
helm install sync recluster-sync/chart \
  --set image.repository=$REG/recluster-sync --set image.tag=dev --set mode=kwok -n kube-system