/*
Copyright 2025 LC.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RcNodeStorageSpecApplyConfiguration represents a declarative configuration of the RcNodeStorageSpec type for use
// with apply.
type RcNodeStorageSpecApplyConfiguration struct {
	Name *string `json:"name,omitempty"`
	Size *int64  `json:"size,omitempty"`
}

// RcNodeStorageSpecApplyConfiguration constructs a declarative configuration of the RcNodeStorageSpec type for use with
// apply.
func RcNodeStorageSpec() *RcNodeStorageSpecApplyConfiguration {
	return &RcNodeStorageSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *RcNodeStorageSpecApplyConfiguration) WithName(value string) *RcNodeStorageSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *RcNodeStorageSpecApplyConfiguration) WithSize(value int64) *RcNodeStorageSpecApplyConfiguration {
	b.Size = &value
	return b
}
